services:
  node:
    image: node:21.5-bullseye-slim
    container_name: e-motion-web
    working_dir: /e-motion-web
    volumes:
      - .:/e-motion-web
    restart: unless-stopped
    tty: true
    ports:
      - ${DOCKER_APP_HOST_PORT:-3000}:3000
    command: bash -c "npm install && npm run dev"
