services:
  node:
    image: node:21.5-bullseye-slim
    container_name: e-motion-web
    working_dir: /application
    volumes:
      - .:/application
    restart: unless-stopped
    tty: true
    ports:
      - ${EXTERNAL_NODE_PORT:-3000}:3000
    command: ["npm", "run", "dev"]
